spring:
  application:
    name: NBEProject

  thymeleaf:
    cache: false
    prefix: classpath:templates/

  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 613550923094-998bdotlojba1bjavt85e18dtgcp82dv.apps.googleusercontent.com
            client-secret: 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
            scope: #어떤 정보 가져올건지
              - email
              - profile
          facebook:
            client-id: 1208804653811097
            client-secret: 36416587d0ff062e744610a92868acfb
            scope: # 접근권한
              - email
              - public_profile
          naver:
            client-id: TAkbCCstmahX0oZ76Vgn
            client-secret: mtlGCe89D2
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: f800779d6d479b216bdc5f6e0c213c7d
            client-secret: OgSVI4linfmb3NcpnfTwGNLKBBpyWFnP
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m


app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 5 # 한 [페이징] 당 몇 개의 페이지를 표시
    page_rows: 15 # 한 '페이지' 에 몇 개의 글을 리스트 할 지?

  # 파일 업로드 경로
  upload:
    path: NBEProject/upload
