spring:
  application:
    name: NBEProject
#  datasource:
#    url: jdbc:mysql://192.168.0.81:3306/nbe_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: Admin
#    password: 1234

  thymeleaf:
    cache: false
    prefix: classpath:templates/

#  datasource:
#    url: jdbc:mysql://localhost:3306/show_table
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: abc111
#    password: 1234

  datasource:
    url: jdbc:mysql://192.168.0.81:3306/nbe_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Admin
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 5 # 한 [페이징] 당 몇 개의 페이지를 표시
    page_rows: 5 # 한 '페이지' 에 몇 개의 글을 리스트 할 지?

  # 파일 업로드 경로
  upload:
    path: NBEProject/upload
